export default {
	// loading
	SHOW_LOADING: 'SHOW_LOADING',
	HIDE_LOADING: 'HIDE_LOADING',

	// toast 消息
	TOAST: 'TOAST',
	UPDATE_TOAST_LIST: 'UPDATE_TOAST_LIST',

	//
	BEGIN_PRORESS: 'BEGIN_PRORESS',
	STOP_PRORESS: 'STOP_PRORESS',

	// 弹窗
	ALERT: 'ALERT',
	UPDATE_ALERT: 'UPDATE_ALERT',

	// 用户信息
	GET_USER_LOGIN_INFO: 'GET_USER_LOGIN_INFO',

	//注册
	GO_REGISTER_CHECK: 'GO_REGISTER_CHECK',
	CHECK_MOBILE_FETCH: 'CHECK_MOBILE_FETCH',
	DO_REGISTER: 'DO_REGISTER',
	REGISTER_CODE_FETCH: 'REGISTER_CODE_FETCH',
	SEND_REGISTER_CODE: 'SEND_REGISTER_CODE',

	//账单详情
	GET_ONECARD: 'GET_ONECARD',
	ONECARD_INFO_FETCH: 'ONECARD_INFO_FETCH',
	GET_BILL: 'GET_BILL',
	BILL_INFO_FETCH: 'BILL_INFO_FETCH',

	//记账收支详情
	GET_CHARTS: 'GET_CHARTS',
	CHART_INFO_FETCH: 'CHART_INFO_FETCH',

	//征信
	SEACH_CREDIT: 'SEACH_CREDIT',
	CREDIT_INFO_FETCH: 'CREDIT_INFO_FETCH',
	//注册邮箱
    GO_REGISTER_EMAIL: 'GO_REGISTER_EMAIL',
    CHECK_EMAIL_FETCH: 'CHECK_EMAIL_FETCH',
    DO_CADASTRAR: 'DO_CADASTRAR',
    EMAIL_CODE_FETCH: 'EMAIL_CODE_FETCH',
    SEND_EMAIL_CODE: 'SEND_EMAIL_CODE',

	//帮助中心
	GET_HELP_CENTER:'GET_HELP_CENTER',

}