const COMMON_BR = {
    "COMMON_SEACH": "Consultar",
    "COMMON_RESEACH": "Consultar de novo",
    "COMMON_NO_RESEACH": "Agora não",
    "COMMON_CONTINU_RESEACH": "Continuar",
    "COMMON_STATUS_PAY": "Pagar agora",
    "COMMON_STATUS_REPAY": "Já paga",
    "COMMON_STATUS_NOPAY": "Não paga",
    "COMMON_STATUS_NOOUT": "Não sai",
    "COMMON_STATUS_OVERDIE": "inclui atraso",
    "COMMON_CANCEL": "Cancelar",
    "COMMON_OK": "Confirmar",
    "COMMON_PAID_OFF": "Já quitou",
    "COMMON_PAID_YES": "Sim",
    "COMMON_PAID_NO": "Não",
    "COMMON_PAID_NOBIND": "Agora não vincular",
    "COMMON_PAID_BIND": "Vai para vincular",
    "COMMON_HELPCENTER": "Centro de ajuda",
    "COMMON_PRODUCTFEEDBACK":"Feedback de produto",
    "COMMON_PRIVACYAGREEMENT":"Política de privacidade",
    "COMMON_DELETE_CARD":"Deletar cartão",
    "COMMON_QUS_BACK":"Feedback de perguntas",
    "COMMON_DELET":"Já decidi deletar",
    "COMMON_THINK":"Deixe-me pensar",
    "COMMON_TIP":"Aviso",
    "COMMON_DELET_TXT":"Depois de deletar, os históricos da sua fatura do cartão de crédito serão perdidos, confirme se deleta ou não",
    "COMMON_SYS_TIP":"Consulta de crédito está em elevação, por favor, aguarde.",
}

const COMMON_ZH = {
    "COMMON_SEACH": "查询",
    "COMMON_RESEACH": "重新查询",
    "COMMON_NO_RESEACH": "暂不查询",
    "COMMON_CONTINU_RESEACH": "继续查询",
    "COMMON_STATUS_PAY": "立即还款",
    "COMMON_STATUS_REPAY": "已还",
    "COMMON_STATUS_NOPAY": "未还",
    "COMMON_STATUS_NOOUT": "未出账",
    "COMMON_STATUS_OVERDIE": "含逾期",
    "COMMON_CANCEL": "取消",
    "COMMON_OK": "确定",
    "COMMON_PAID_OFF": "已还清",
    "COMMON_PAID_YES": "是",
    "COMMON_PAID_NO": "否",
    "COMMON_PAID_NOBIND": "暂不绑定",
    "COMMON_PAID_BIND": "去绑定",
    "COMMON_HELPCENTER": "帮助中心",
    "COMMON_PRODUCTFEEDBACK":"产品反馈",
    "COMMON_PRIVACYAGREEMENT":"隐私协议",
    "COMMON_DELETE_CARD":"删除卡片",
    "COMMON_QUS_BACK":"问题反馈",
    "COMMON_DELET":"决定删除",
    "COMMON_THINK":"我再想想",
    "COMMON_TIP":"提示",
    "COMMON_DELET_TXT":"确认删除后，您的该信用卡账单记录将被清空请确认是否删除",
    "COMMON_SYS_TIP":"征信查询正在升级中，敬请等待",
}


export {
    COMMON_BR,
    COMMON_ZH
}